name: Publish And Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install and Build
        run: |
          yarn add install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: master # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
